project_id = "yafjkpckhzpkrptmzcms"

[functions.create-zoom-meeting]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.notify-quiz-assignment]
verify_jwt = false
